//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.PrismRefactorings.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DD.PrismRefactorings.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Gets or sets the name.
        ////// &lt;/summary&gt;
        ///public string Name { get; set; }.
        /// </summary>
        internal static string NoClassDeclaration {
            get {
                return ResourceManager.GetString("NoClassDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private string name;
        ///
        ////// &lt;summary&gt;
        ////// Gets or sets the name.
        ////// &lt;/summary&gt;
        ///public string Name { get =&gt; this.name; set =&gt; this.SetProperty(ref this.name, value); }.
        /// </summary>
        internal static string NoClassDeclarationRefactored {
            get {
                return ResourceManager.GetString("NoClassDeclarationRefactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModel.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModel : BindableBase
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Gets or sets the name.
        ///        /// &lt;/summary&gt;
        ///        public string Name { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModel {
            get {
                return ResourceManager.GetString("SampleViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModel.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModel : BindableBase
        ///    {
        ///        private string name;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Gets or sets the name.
        ///        /// &lt;/summary&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelRefactored {
            get {
                return ResourceManager.GetString("SampleViewModelRefactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithCtor.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithCtor : BindableBase
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Initializes a new instance of the &lt;see cref=&quot;SampleViewModelWi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithCtor {
            get {
                return ResourceManager.GetString("SampleViewModelWithCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithCtorAndFields.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithCtorAndFields : BindableBase
        ///    {
        ///        private readonly string name = &quot;Mike&quot;;
        ///        private readonly int an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithCtorAndFields {
            get {
                return ResourceManager.GetString("SampleViewModelWithCtorAndFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithCtorAndFields.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithCtorAndFields : BindableBase
        ///    {
        ///        private readonly string name = &quot;Mike&quot;;
        ///        private readonly int an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithCtorAndFieldsRefactored {
            get {
                return ResourceManager.GetString("SampleViewModelWithCtorAndFieldsRefactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithCtor.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithCtor : BindableBase
        ///    {
        ///        private string name;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Initializes a new instance of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithCtorRefactored {
            get {
                return ResourceManager.GetString("SampleViewModelWithCtorRefactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithFields.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithFields : BindableBase
        ///    {
        ///        private readonly string name = &quot;Mike&quot;;
        ///        private readonly int answer = 42;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithFields {
            get {
                return ResourceManager.GetString("SampleViewModelWithFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;copyright file=&quot;SampleViewModelWithFields.cs&quot; company=&quot;Daniel Dreibrodt&quot;&gt;
        ///// Copyright (c) Daniel Dreibrodt. All rights reserved.
        ///// &lt;/copyright&gt;
        ///
        ///namespace DD.PrismRefactorings.Tests.ViewModels
        ///{
        ///    using Prism.Mvvm;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A sample view model.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Prism.Mvvm.BindableBase&quot; /&gt;
        ///    public class SampleViewModelWithFields : BindableBase
        ///    {
        ///        private readonly string name = &quot;Mike&quot;;
        ///        private readonly int answer = 42;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleViewModelWithFieldsRefactored {
            get {
                return ResourceManager.GetString("SampleViewModelWithFieldsRefactored", resourceCulture);
            }
        }
    }
}
